baseURL = "https://guy-evans.com"
theme = "DoIt"
title = "Guy Evans"
description = "Sysadmin -- Net Admin -- IT Tech -- DIYer"

enableEmoji = true

enableRobotsTXT = true

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"
[outputs]
  home = ["HTML", "RSS", "JSON"]
# page = ["HTML", "RSS", "JSON"]
#   section = ["HTML", "RSS"]
#   taxonomy = ["HTML", "RSS"]
#   taxonomyTerm = ["HTML"]
[params]

  version = "0.3.X"
  # website title
  title = "Guy Evans"
  description = "Sysadmin -- Net Admin -- IT Tech -- DIYer"
  
  # [Experimental] cache remote images in markdown, more info: https://github.com/HEIGE-PCloud/DoIt/pull/860#issue-1574342372
  cacheRemoteImages = true
  # [Experimental] generate image srcset attribute with hugo image processing feature.
  optimizeImages = true
  # [Experimental] resize method for srcset attribute in optimizeImages, more info: https://gohugo.io/content-management/image-processing/#image-processing-options
  srcsetSmallResizeMethod = "700x webp Lanczos q75"
  srcsetDefaultResizeMethod = "1200x webp Lanczos q75"
  srcsetLargeResizeMethod = "2000x webp Lanczos q75"

  # Do it version

  [params.image]
    # cache remote images for better optimisations
    cacheRemote = false
    # Image resizing and optimisation
    optimise = true

  [params.page]
   [params.page.toc]
      # whether to enable the table of the contents
      enable = true
      keepStatic = false
      # whether to make the table of the contents in the sidebar automatically collapsed
      auto = true
    [params.page.related]
      enable = true
      count = 5
    [params.page.code]
      # the maximum number of lines of displayed code by default
      maxShownLines = 20
    [params.page.comment]
      enable = true
      [params.page.comment.remark42]
        enable = true
        host = "https://comments.evans.fr"
        site_id = "guy-evans.com"
        max_shown_comments = 15
        show_email_subscription = true
        simple_view = false
      # [params.page.comment.isso]
      #   enabled = true
      #   data = "https://isso.evans.fr/"
      #   id = "thread-id"
      #   css = true
      #   lang = ""
      #   replyToSelf = true
      #   requireAuthor = true
      #   requireEmail = false
      #   avatar = true
      #   avatar-bg = "#f0f0f0"
      #   jsLocation = "https://isso.evans.fr/js/embed.min.js"

# # language code ["en", "zh-CN", "fr", "pl", ...]
# languageCode = "en"
# # language name ["English", "简体中文", "Français", "Polski", ...]
# languageName = "English"

defaultContentLanguage = "en"

 [params.app]
    # whether to omit favicon resource links
    noFavicon = true


[languages]
  [languages.en]
    weight = 1
    languageCode = "en"
    languageName = "English"
    [[languages.en.menu.main]]
      weight = 1
      identifier = "posts"
      pre = ""
      post = ""
      name = "Posts"
      url = "/posts/"
      title = ""
    [[languages.en.menu.main]]
      weight = 2
      identifier = "about"
      pre = ""
      post = ""
      name = "~ Whoami"
      url = "/about/"
      title = ""
    [languages.en.params.sponsor]
        enable = true
        bio = "If you find this post helpful, please consider buying me a coffee. Thank you!"
        #link = "https://buymeacoffee.com/guyevans"
        custom = "<a href=\"https://buymeacoffee.com/guyevans\" target=\"_blank\"><center><img src=\"https://cdn.buymeacoffee.com/buttons/v2/default-yellow.png\" alt=\"Buy Me A Coffee\" style=\"height: 55px !important;width: 155 !important;\" ></center></a>"

  [languages.fr]
    weight = 2
    languageCode = "fr"
    languageName = "Français"
    [[languages.fr.menu.main]]
      weight = 1
      identifier = "posts"
      pre = ""
      post = ""
      name = "Postes"
      url = "/posts/"
      title = ""
    [[languages.fr.menu.main]]
      weight = 2
      identifier = "about"
      pre = ""
      post = ""
      name = "~ Whoami"
      url = "/about/"
      title = ""
    [languages.fr.params.sponsor]
        enable = true
        bio = "Si ce post vous a été utile, vous pouvez m'offrir un café. Merci!"
        #link = "https://buymeacoffee.com/guyevans"
        custom = "<a href=\"https://buymeacoffee.com/guyevans\" target=\"_blank\"><center><img src=\"https://cdn.buymeacoffee.com/buttons/v2/default-yellow.png\" alt=\"Buy Me A Coffee\" style=\"height: 55px !important;width: 155 !important;\" ></center></a>"





[params.header]
    [params.header.title]
      # URL of the LOGO
      logo = ""
      # title name
      name = "Guy Evans"
      # you can add extra information before the name (HTML format is supported), such as icons
      # pre = "<i class='far fa-kiss-wink-heart fa-fw' aria-hidden='true'></i>"
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      # whether to use typeit animation for title name
      typeit = false

    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      avatarURL = "https://guy-evans.com/img/ge-profile-2.jpg"
      # title shown in home page (HTML format is supported)
      title = "Guy Evans"
      # subtitle shown in home page (HTML format is supported)
      subtitle = "Sysadmin -- Net Admin -- IT Tech -- DIYer"
      # whether to use typeit animation for subtitle
      typeit = true
      # whether to show social links
      social = true

# Author confi
[author]
  name = "Guy Evans"
  email = "web@evans.fr"
  link = "https://guy-evans.com"
  avatar = "/img/ge-profile-2.jpg"

[params.social]
    # Linkedin = ""
    Twitter = "_guyevans"
    Instagram = "_guyevans"
    # Telegram = "guye06"
    Bluesky = "guy.evans.fr"
    Mastodon = "https://mastodon.xyz/@_guyevans"
    # GitHub = ""
    RSS = true 
# Menu config

[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
  # [[menu.main]]
  #   weight = 2
  #   identifier = "tags"
  #   pre = ""
  #   post = ""
  #   name = "Tags"
  #   url = "/tags/"
  #   title = ""
  # [[menu.main]]
  #   weight = 3
  #   identifier = "categories"
  #   pre = ""
  #   post = ""
  #   name = "Categories"
  #   url = "/categories/"
  #   title = ""

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

[params.analytics]
    enable = true
    # Umami
    # [params.analytics.umami]
    #   id = ""
    #   websiteId = "4d8524a0-ef19-4b23-bf6b-fa76b7614903"
    #   jsLocation = "https://umami.evans.fr/umami.js"
    
    [params.analytics.matomo]
      url = "//matomo.evans.fr/"


[params.search]
  enable = false
  # type of search engine ("algolia", "fuse")
  type = "fuse"
  # max index length of the chunked content
  contentLength = 4000
  # placeholder of the search bar
  placeholder = ""
  # DoIt NEW | 0.2.1 max number of results length
  maxResultLength = 10
  # DoIt NEW | 0.2.3 snippet length of the result
  snippetLength = 30
  [params.search.fuse]
    #  [DoIt NEW | 0.2.12]  https://fusejs.io/api/options.html
    isCaseSensitive = false
    minMatchCharLength = 2
    findAllMatches = false
    location = 0
    threshold = 0.3
    distance = 100
    ignoreLocation = false
    useExtendedSearch = true
    ignoreFieldNorm = false