backend:
  name: github
  branch: master # Branch to update (optional; defaults to master)
  repo: guyaevans/guyevans.github.io
publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img
site_url: https://guy-evans.com
i18n:
  structure: multiple_files
  locales: [en, fr]
  default_locale: en

collections:
  - name: pages
    label: Pages
    delete: false
    files:
      - name: about-en
        label: About Page EN
        file: content/about/index.en.md
        i18n: true
        fields:
          - { label: Title, name: title, widget: string }
          - label: Body
            name: body
            widget: markdown
      - name: about-fr
        label: About Page FR
        file: content/about/index.fr.md
        i18n: true
        fields:
          - { label: Titre, name: titre, widget: string }
          - label: Body
            name: body
            widget: markdown
  - name: posts
    label: Posts
    folder: content/posts
    # structure: multiple_files
    create: true
    i18n: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    path: '{{slug}}/index'
    fields:
      - label: Title
        name: title
        widget: string
        i18n: true 
      - label: Date
        name: date
        widget: datetime
        i18n: duplicate
      - {label: "Featured Image", name: "featuredImage", widget: "image", required: false, i18n: duplicate}
      - label: Tags
        name: tags
        widget: list
        i18n: true
        required: false
      - name: series
        label: Series
        widget: list
        i18n: true
        required: false
      - label: Full Text RSS
        name: rssFullText
        widget: boolean
        default: true
      - label: Light Gallery
        name: lightgallery
        widget: boolean
        default: true
      - label: Body
        name: body
        widget: markdown
        i18n: true 
